services:
  lunaris-backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: lunaris-backend
    command: /bin/sh -c "npx prisma generate && npm run start:dev"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3001:3001' 
      - '5555:5555' 
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgresql://lunaris:lunaris@lunaris-db:5432/lunaris_db?schema=public
      - CORS_ORIGINS=http://localhost:3000
    env_file:
      - .env
    depends_on:
      lunaris-db:
        condition: service_healthy
    restart: unless-stopped

  lunaris-db:
    image: postgres:16-alpine
    container_name: lunaris-db
    environment:
      POSTGRES_USER: lunaris
      POSTGRES_PASSWORD: lunaris
      POSTGRES_DB: lunaris_db
    ports:
      - '5432:5432'
    volumes:
      - lunaris_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U lunaris -d lunaris_db']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  lunaris_db_data:
    driver: local